# Generated by Django 4.0.4 on 2022-05-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=1)),
                ('civil_status', models.CharField(choices=[('s', 'Single'), ('m', 'Married'), ('w', 'Widower'), ('d', 'Divorced')], max_length=1)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
